framework:
  messenger:
    failure_transport: failed
    transports:
      failed: 'doctrine://default?queue_name=failed'
      telegram:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        serializer: messenger.transport.symfony_serializer
        retry_strategy:
          max_retries: 5
          delay: 2000               # первая задержка 2 секунды
          multiplier: 2             # каждый следующий retry ×2
          max_delay: 30000          # не больше 30 секунд
        options:
          exchange:
            name: 'telegram_confirmation'
            type: direct

    routing:
      'App\Message\SendTelegramConfirmationCode': telegram

      # Route your messages to the transports
      # 'App\Message\YourMessage': async
