services:
  ###> doctrine/doctrine-bundle ###
  news-portal-database:
    restart: always
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-cm_local_db}
      MYSQL_USER: ${MYSQL_USER:-cm_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeRoot!}
    container_name: "${APP_NAME}-database"
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "${MYSQL_HOST:-127.0.0.1}"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - news-portal_data:/var/lib/mysql:rw

volumes:
  ###> doctrine/doctrine-bundle ###
  news-portal_data:
  ###< doctrine/doctrine-bundle ###
