services:
  ###> doctrine/doctrine-bundle ###
  news-portal-database:
    restart: always
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-cm_local_db}
      MYSQL_USER: ${MYSQL_USER:-cm_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeRoot!}
    container_name: "${APP_NAME}-database"
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "${MYSQL_HOST:-127.0.0.1}" ]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - news-portal_data:/var/lib/mysql:rw
    ###< doctrine/doctrine-bundle ###
    ###> rabbitmq ###
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "${APP_NAME}-rabbitmq"
    hostname: "${APP_NAME}-rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - "${RABBITMQ_AMQP_PORT:-5672}:5672"         # AMQP порт
      - "${RABBITMQ_UI_PORT:-15672}:15672"         # Web UI: http://localhost:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
  ###< rabbitmq ###

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    container_name: "${APP_NAME}-mercure"
    environment:
      # Uncomment the following line to disable HTTPS,
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeThisMercureHubJWTSecretKey!}
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8001 http://192.168.1.104:8001 http://5.35.12.147:8000 http://5.35.12.147:80
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    ports:
      - "${MERCURE_CLIENT_PORT:-80}:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
#      - ./docker/mercure/dev.Caddyfile:/etc/caddy/dev.Caddyfile:ro
###< symfony/mercure-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  news-portal_data:
  ###< doctrine/doctrine-bundle ###
  ###> rabbitmq ###
  rabbitmq_data:
  ###< rabbitmq ###

###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
